version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: pip
    directory: /services/semantic-gateway
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: terraform
    directory: /infra/terraform/environments/dev
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
  - package-ecosystem: docker
    directory: /services/semantic-gateway
    schedule:
      interval: weekly
    open-pull-requests-limit: 3
